### ISSUE TITLE
Build status chart flickers when hovering over the infobox

### ISSUE THREAD

**Issue by rillig** [bsiegert/BulkTracker#46]
On https://releng.netbsd.org/bulktracker/build/42, hover over the build status infobox:
> ![image](https://github.com/bsiegert/BulkTracker/assets/3233724/99670223-50bd-413e-81f3-12e1c6b6800b)

When the mouse cursor is both over the pie chart circle and in the infobox rectangle, the infobox flickers.

**Comment by bsiegert** [comment]
That's an upstream issue in the Google chart API, I assume :( I have seen it happen but it depends on the window size and browser.

Since the Chart API is deprecated anyway, maybe it's time to switch to an alternative? quickchart.io seems nice.

**Comment by bsiegert** [comment]
We can use chart.js instead of the Google Chart API! That also means that we can get rid of this external API dependency, which is good news.

Here is some example code to render a chart -- unfortunately, GitHub does not let me attach an HTML file to a comment.

```html
<!doctype html>

<html>
<body>

<div>
  <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: ['OK', 'prefailed', 'indirect-failed', 'failed'],
      datasets: [{
        data: [26991, 1202, 838, 276],
	backgroundColor: [
			'green',
			'blue',
			'orange',
			'red',
	],
        borderWidth: 1
      }]
    }
  });
</script>

</body>
```

which ends up looking like the picture. 
![Screenshot 2024-05-07 10 50 17](https://github.com/bsiegert/BulkTracker/assets/866330/99384264-2447-4578-b62c-fb0f045a1d6a)

**Comment by bsiegert** [comment]
This will be in the next release.
